#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.

FILE='/etc/passwd'

while read -r line; do
    username=$(echo "$line" | cut  --delimiter=':'  --fields=1)
    id=$(echo "$line" | cut --delimiter=':'  --fields=3)
    home=$(echo "$line" | cut --delimiter=':'  --fields=6)
    echo "$username":"$id":"$home"
done < $FILE
