#!/usr/bin/env bash
# Prints "Best School" 10 times using while, but says Hi on 9th iteration

i=0
while [ $i -lt 10 ]; do
    echo "Best School"
    if [ $i = 8 ]
    then
        echo "Hi"
    fi
    ((i+=1))
done
