#!/usr/bin/env bash
# Prints numbers from 1 to 20, but prints different on 4, 9 and 17

i=1
while [ $i -le 20 ]; do
    echo "$i"
    case "$i" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((i+=1))
done
