#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
echo "$$" > /var/run/holbertonscript.pid

while true
do
    echo "To infinity and beyond"
    trap "echo Y U no love me?!" SIGINT
    trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
    sleep 2
done
