#!/usr/bin/env bash
#Script that print "To infinity and beyond"
# shellcheck disable=SC200

case "$1" in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        #kill "$(pgrep -f manage_my_process)"
        pkill -f "bash ./manage_my_process"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        #kill "$(pgrep -f manage_my_process)"
        pkill -f "bash ./manage_my_process"
        rm /var/run/my_process.pid 
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
